
  footprint: [[0.7, 0.25], [0.7, -0.25], [-0.1, -0.25], [-0.1, 0.25]]

  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1
  publish_frequency: 2
  static_map: true
  rolling_window: false
  resolution: 0.05
  map_type: costmap
  transform_tolerance: 1.0

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  3  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     1.5  # 2.5 max. distance from an obstacle at which costs are incurred for planning paths.

  static_layer:
    enabled:              true
    # map_topic:            "/cover_clean/map"
    map_topic:            "/map"

